### ISSUE TITLE
Problem validating BODS json without a 'statementDate'

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#20]
statementDate is not a required field. When I run this example file ([4a-simple-pep-declaration.json](https://github.com/openownership/data-standard/blob/0.2-dev/examples/4a-simple-pep-declaration.json)) through CoVE, I get the following error:
 
```
Traceback (most recent call last):
  File "/home/kadie/code/lib-cove-bods/.ve/bin/libcovebods", line 11, in <module>
    load_entry_point('libcovebods', 'console_scripts', 'libcovebods')()
  File "/home/kadie/code/lib-cove-bods/libcovebods/cli/__main__.py", line 19, in main
    file_type='json'
  File "/home/kadie/code/lib-cove-bods/libcovebods/api.py", line 38, in bods_json_output
    common_checks_bods(context, output_dir, json_data, schema_bods, lib_cove_bods_config=lib_cove_bods_config)
  File "/home/kadie/code/lib-cove-bods/libcovebods/common_checks.py", line 18, in common_checks_bods
    'statistics': get_statistics(json_data),
  File "/home/kadie/code/lib-cove-bods/libcovebods/lib/common_checks.py", line 79, in get_statistics
    year = int(statement['statementDate'].split('-')[0])
KeyError: 'statementDate'
```

**Comment by ScatteredInk** [comment]
This is fixed.
